name: tasktodo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ✅ Riverpod for state management
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # ✅ Riverpod lints (recommended)
  riverpod_lint: ^2.3.10
  custom_lint: ^0.6.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash.png
    - assets/images/onboard1.png
    - assets/images/onboard2.png
    - assets/images/onboard3.png
