name: tasktodo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management & Networking
  flutter_riverpod: ^2.5.1
  dio: ^5.4.0

  # Firebase
  firebase_core: ^3.4.0
  cloud_firestore: ^5.4.2
  cloud_functions: ^5.0.5

  # Camera
  camera: ^0.10.5+5

  # Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Riverpod linting
  riverpod_lint: ^2.3.10
  custom_lint: ^0.7.3

  # Code generation
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
